version: "3.8"

services:
    frontend:
        build:
            context: ./config
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./:/project

